# Fish and Pure colors from the Noctalia palette.
# Generated by Noctalia from ~/.config/noctalia/templates/fish-colors.fish into
# ~/.config/fish/conf.d/noctalia-colors.fish: edit the template, not this file.
# New shells pick up a palette or mode change; running shells keep the old one.

set -g fish_color_normal e8eaed
set -g fish_color_command 81c995 --bold
set -g fish_color_keyword f28b82
set -g fish_color_quote fdd663
set -g fish_color_redirection 78d9ec
set -g fish_color_end 25e075
set -g fish_color_error f28b82 --bold
set -g fish_color_param e8eaed
set -g fish_color_comment 80868b --italics
set -g fish_color_selection 121212 --background=25e075
set -g fish_color_search_match 121212 --background=fdd663
set -g fish_color_operator 78d9ec
set -g fish_color_escape c58af9
set -g fish_color_autosuggestion 80868b
set -g fish_pager_color_progress 80868b
set -g fish_pager_color_prefix 81c995 --bold
set -g fish_pager_color_completion e8eaed
set -g fish_pager_color_description 80868b

# Pure: neutral context, accent prompt, red only for errors.
set -g pure_color_primary 25e075
set -g pure_color_info 25e075
set -g pure_color_mute 80868b
set -g pure_color_success 25e075
set -g pure_color_danger f28b82
set -g pure_color_warning 80868b
set -g pure_color_current_directory e8eaed
set -g pure_color_git_branch 80868b
set -g pure_color_git_dirty 25e075
set -g pure_color_git_stash 80868b
set -g pure_color_git_unpushed_commits 80868b
set -g pure_color_git_unpulled_commits 80868b
set -g pure_color_command_duration 80868b
set -g pure_color_prompt_on_success 25e075
set -g pure_color_prompt_on_error f28b82
set -g pure_color_exit_status f28b82
