" Lean Material 2 Vim setup with no plugin dependency.
set termguicolors
set number
set relativenumber
set cursorline
set signcolumn=yes
set laststatus=2
set noshowmode
set mouse=a
set ignorecase
set smartcase
set incsearch
set hlsearch
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Colors are rendered from the Noctalia palette into ~/.vim/colors/noctalia.vim;
" the colorscheme also sets 'background' to follow the dark or light mode.
silent! colorscheme noctalia
