color0 #3c4043
color1 #f28b82
color2 #81c995
color3 #fdd663
color4 #8ab4f8
color5 #c58af9
color6 #78d9ec
color7 #dadce0
color8 #80868b
color9 #f6aea9
color10 #a8dab5
color11 #fde293
color12 #aecbfa
color13 #d7aefb
color14 #a1e4f2
color15 #f8f9fa

cursor                #25e075
cursor_text_color     #121212
background            #121212
foreground            #e8eaed
selection_foreground  #e8eaed
selection_background  #174a2b
active_border_color   #25e075
inactive_border_color #2c2c2c
url_color             #25e075

active_tab_foreground   #082613
active_tab_background   #25e075
inactive_tab_foreground #bdc1c6
inactive_tab_background #2c2c2c
cursor_trail_color      #bdc1c6
