# Fish and Pure colors from the Noctalia palette.
# Generated by Noctalia from ~/.config/noctalia/templates/fish-colors.fish into
# ~/.config/fish/conf.d/noctalia-colors.fish: edit the template, not this file.
# New shells pick up a palette or mode change; running shells keep the old one.

set -g fish_color_normal {{colors.terminal_foreground.default.hex_stripped}}
set -g fish_color_command {{colors.terminal_normal_green.default.hex_stripped}} --bold
set -g fish_color_keyword {{colors.terminal_normal_red.default.hex_stripped}}
set -g fish_color_quote {{colors.terminal_normal_yellow.default.hex_stripped}}
set -g fish_color_redirection {{colors.terminal_normal_cyan.default.hex_stripped}}
set -g fish_color_end {{colors.primary.default.hex_stripped}}
set -g fish_color_error {{colors.terminal_normal_red.default.hex_stripped}} --bold
set -g fish_color_param {{colors.terminal_foreground.default.hex_stripped}}
set -g fish_color_comment {{colors.terminal_bright_black.default.hex_stripped}} --italics
set -g fish_color_selection {{colors.terminal_background.default.hex_stripped}} --background={{colors.primary.default.hex_stripped}}
set -g fish_color_search_match {{colors.terminal_background.default.hex_stripped}} --background={{colors.terminal_normal_yellow.default.hex_stripped}}
set -g fish_color_operator {{colors.terminal_normal_cyan.default.hex_stripped}}
set -g fish_color_escape {{colors.terminal_normal_magenta.default.hex_stripped}}
set -g fish_color_autosuggestion {{colors.terminal_bright_black.default.hex_stripped}}
set -g fish_pager_color_progress {{colors.terminal_bright_black.default.hex_stripped}}
set -g fish_pager_color_prefix {{colors.terminal_normal_green.default.hex_stripped}} --bold
set -g fish_pager_color_completion {{colors.terminal_foreground.default.hex_stripped}}
set -g fish_pager_color_description {{colors.terminal_bright_black.default.hex_stripped}}

# Pure: neutral context, accent prompt, red only for errors.
set -g pure_color_primary {{colors.primary.default.hex_stripped}}
set -g pure_color_info {{colors.primary.default.hex_stripped}}
set -g pure_color_mute {{colors.terminal_bright_black.default.hex_stripped}}
set -g pure_color_success {{colors.primary.default.hex_stripped}}
set -g pure_color_danger {{colors.terminal_normal_red.default.hex_stripped}}
set -g pure_color_warning {{colors.terminal_bright_black.default.hex_stripped}}
set -g pure_color_current_directory {{colors.terminal_foreground.default.hex_stripped}}
set -g pure_color_git_branch {{colors.terminal_bright_black.default.hex_stripped}}
set -g pure_color_git_dirty {{colors.primary.default.hex_stripped}}
set -g pure_color_git_stash {{colors.terminal_bright_black.default.hex_stripped}}
set -g pure_color_git_unpushed_commits {{colors.terminal_bright_black.default.hex_stripped}}
set -g pure_color_git_unpulled_commits {{colors.terminal_bright_black.default.hex_stripped}}
set -g pure_color_command_duration {{colors.terminal_bright_black.default.hex_stripped}}
set -g pure_color_prompt_on_success {{colors.primary.default.hex_stripped}}
set -g pure_color_prompt_on_error {{colors.terminal_normal_red.default.hex_stripped}}
set -g pure_color_exit_status {{colors.terminal_normal_red.default.hex_stripped}}
