" Vim colors from the Noctalia palette.
" Generated by Noctalia from ~/.config/noctalia/templates/vim-colors.vim into
" ~/.vim/colors/noctalia.vim: edit the template, not this file.
set background={{ mode }}
highlight clear
if exists('syntax_on')
    syntax reset
endif
let g:colors_name = 'noctalia'

highlight Normal       guifg={{colors.terminal_foreground.default.hex}} guibg={{colors.terminal_background.default.hex}}
highlight NormalNC     guifg={{colors.on_surface_variant.default.hex}} guibg={{colors.terminal_background.default.hex}}
highlight CursorLine                  guibg={{colors.surface_container_low.default.hex}}
highlight LineNr       guifg={{colors.terminal_bright_black.default.hex}} guibg={{colors.terminal_background.default.hex}}
highlight CursorLineNr guifg={{colors.terminal_normal_yellow.default.hex}} guibg={{colors.surface_container_low.default.hex}} gui=bold
highlight Comment      guifg={{colors.terminal_bright_black.default.hex}} gui=italic
highlight Constant     guifg={{colors.terminal_normal_magenta.default.hex}}
highlight String       guifg={{colors.terminal_normal_green.default.hex}}
highlight Identifier   guifg={{colors.terminal_normal_blue.default.hex}}
highlight Statement    guifg={{colors.terminal_normal_red.default.hex}} gui=bold
highlight PreProc      guifg={{colors.terminal_normal_blue.default.hex}}
highlight Type         guifg={{colors.terminal_normal_yellow.default.hex}}
highlight Special      guifg={{colors.terminal_normal_cyan.default.hex}}
highlight Visual       guifg={{colors.on_primary.default.hex}} guibg={{colors.primary.default.hex}}
highlight Search       guifg={{colors.terminal_background.default.hex}} guibg={{colors.terminal_normal_yellow.default.hex}}
highlight StatusLine   guifg={{colors.on_primary.default.hex}} guibg={{colors.primary.default.hex}} gui=bold
highlight StatusLineNC guifg={{colors.on_surface_variant.default.hex}} guibg={{colors.surface_container.default.hex}}
highlight VertSplit    guifg={{colors.surface_container.default.hex}} guibg={{colors.terminal_background.default.hex}}
highlight ErrorMsg     guifg={{colors.terminal_normal_red.default.hex}} guibg={{colors.terminal_background.default.hex}} gui=bold
highlight Pmenu        guifg={{colors.on_surface.default.hex}} guibg={{colors.surface_container.default.hex}}
highlight PmenuSel     guifg={{colors.on_primary.default.hex}} guibg={{colors.primary.default.hex}} gui=bold
